# Generated by Django 3.1.6 on 2021-04-01 13:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None,
                                                                 verbose_name='номер телефона'),
        ),
    ]
