# Generated by Django 3.1.6 on 2021-04-01 14:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_auto_20210401_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='номер телефона'),
        ),
    ]
