# Generated by Django 3.1.6 on 2021-04-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_auto_20210402_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'компания', 'verbose_name_plural': 'компании'},
        ),
    ]
