# Generated by Django 3.1.6 on 2021-04-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_auto_20210402_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['id'], 'verbose_name': 'вакансия', 'verbose_name_plural': 'вакансии'},
        ),
    ]
