# Generated by Django 3.1.6 on 2021-04-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_auto_20210402_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'вакансия', 'verbose_name_plural': 'вакансии'},
        ),
    ]
