# Generated by Django 3.1.6 on 2021-04-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_auto_20210403_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='user/photo', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='company_images/100x60.gif', upload_to='company_images/', verbose_name='логотип'),
        ),
    ]
