# Generated by Django 3.1.6 on 2021-04-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_auto_20210404_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='company_images/100x60.gif', upload_to='company_images', verbose_name='логотип'),
        ),
    ]
