# Generated by Django 3.1.6 on 2021-04-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0013_auto_20210404_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(db_index=True, max_length=10000, verbose_name='описание вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='название вакансии'),
        ),
    ]
