# Generated by Django 3.1.6 on 2021-04-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0017_auto_20210405_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_photo',
            field=models.ImageField(blank=True, upload_to='user_images/photo_application', verbose_name='фотография'),
        ),
    ]
