# Generated by Django 3.1.6 on 2021-04-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0018_auto_20210405_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_photo',
            field=models.ImageField(blank=True, upload_to='user_photo', verbose_name='фотография'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='100x60.gif', upload_to='company_images', verbose_name='логотип'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(default='100x60.gif', upload_to='speciality_images', verbose_name='изображение'),
        ),
    ]
