# Generated by Django 3.1.6 on 2021-04-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0019_auto_20210405_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo', verbose_name='фотография'),
        ),
    ]
