# Generated by Django 3.1.6 on 2021-04-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0021_auto_20210408_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='company_images/100x60.gif', upload_to='company_images', verbose_name='логотип'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(default='speciality_images/100x60.gif', upload_to='speciality_images', verbose_name='изображение'),
        ),
    ]
