# Generated by Django 3.1.6 on 2021-04-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0022_auto_20210410_2128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['id'], 'verbose_name': 'резюме', 'verbose_name_plural': 'резюме'},
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='100x60.gif', upload_to='company_images', verbose_name='логотип'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(default='100x60.gif', upload_to='speciality_images', verbose_name='изображение'),
        ),
    ]
