# Generated by Django 3.1.6 on 2021-04-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0023_auto_20210411_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_photo',
            field=models.ImageField(blank=True, default='100x60.gif', upload_to='user_photo', verbose_name='фотография'),
        ),
    ]
