# Generated by Django 3.1.6 on 2021-04-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0033_auto_20210411_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company_images', verbose_name='логотип'),
        ),
    ]
