# Generated by Django 3.1.6 on 2021-04-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0036_auto_20210418_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(choices=[(1, '0-15'), (2, '15-100'), (3, '0-15'), (4, '15-100'), (5, '0-15')], max_length=10, verbose_name='количество сотрудников'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='grade',
            field=models.IntegerField(choices=[(1, 'Стажер'), (2, 'Джуниор'), (3, 'Миддл'), (4, 'Синьор'), (5, 'Лид')], max_length=10, verbose_name='квалификация'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.IntegerField(choices=[(1, 'Не ищу работу'), (2, 'Рассматриваю предложения'), (3, 'Ищу работу')], max_length=10, verbose_name='готовность к работе'),
        ),
    ]
