# Generated by Django 3.1.6 on 2021-05-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0038_auto_20210418_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(choices=[(1, '0-15'), (2, '15-100'), (3, '100-500'), (4, '500-1000'), (5, '> 1000')], verbose_name='количество сотрудников'),
        ),
    ]
